# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg-api
  labels:
    name: ffmpeg-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 40%
      maxUnavailable: 1
  selector:
    matchLabels:
      name: ffmpeg-api
  template:
    metadata:
      labels:
        name: ffmpeg-api
        version: stable
      # annotations:
      #   gke-gcsfuse/volumes: "true"
    spec:
      restartPolicy: Always
      # serviceAccountName: k8s-sa-cluster
      terminationGracePeriodSeconds: 60
      nodeSelector:
        cloud.google.com/machine-family: n2
        cloud.google.com/compute-class: Performance
      containers:
      - image: ffmpeg-api
        name: ffmpeg-api
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /_healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: ENV
          value: prod
        # TODO: Update prior to deployment
        - name: INPUT_BUCKET
          value: not-in-use
        resources:
          requests: ### CPU based transcoding: N2 custom shape: 36 vCPU, 72GB RAM, 100GB SSD
            cpu: 4 #16
            memory: 16Gi #64Gi
            ephemeral-storage: 200Gi
          limits:
            # cpu: 4 #16
            memory: 16Gi #64Gi
            ephemeral-storage: 200Gi
      #   volumeMounts:
      #   - name: gcs-fuse-csi-gke-input
      #     mountPath: /input
      #   - name: gcs-fuse-csi-gke-event-input
      #     mountPath: /input-event
      #   - name: gcs-fuse-csi-output
      #     mountPath: /output
      # volumes:
      # - name: gcs-fuse-csi-gke-input
      #   csi:
      #     driver: gcsfuse.csi.storage.gke.io
      #     volumeAttributes:
      #       bucketName: gcs-__PROJECT_ID__-__CUSTOMER_ID__-test-input
      #       fileCacheCapacity: "100Gi"
      #       cache-dir: "/var/cache"
      #       enable-parallel-downloads: "true"
      # - name: gcs-fuse-csi-gke-event-input
      #   csi:
      #     driver: gcsfuse.csi.storage.gke.io
      #     volumeAttributes:
      #       bucketName: gcs-__PROJECT_ID__-__CUSTOMER_ID__-test-input
      #       fileCacheCapacity: "100Gi"
      #       cache-dir: "/var/cache"
      #       enable-parallel-downloads: "true"
      # - name: gcs-fuse-csi-output
        # csi:
        #   driver: gcsfuse.csi.storage.gke.io
        #   volumeAttributes:
        #     bucketName: gcs-__PROJECT_ID__-__CUSTOMER_ID__-test-output
        #     fileCacheCapacity: "100Gi"
        #     cache-dir: "/var/cache"
        #     enable-parallel-downloads: "true"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: ffmpeg-api
  name: ffmpeg-api
  # annotations:
  #   networking.gke.io/load-balancer-type: "Internal"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    name: ffmpeg-api
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ffmpeg-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ffmpeg-api
  minReplicas: 2
  maxReplicas: 30
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - periodSeconds: 15
          type: Percent
          value: 50
