name: Terraform Deployment

on:
  workflow_dispatch

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    env:
      GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
      GCP_WI_PROVIDER_ID: ${{ vars.GCP_WI_PROVIDER_ID }}
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud Project
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: sa-tf-gh-actions@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com
          workload_identity_provider: ${{ env.GCP_WI_PROVIDER_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.3"  # Replace with your desired version

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="bucket=bkt-tfstate-${{ env.GCP_PROJECT_ID }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -out=out.tfplan \
            -var "project_id=${{ env.GCP_PROJECT_ID }}" \
            -var "customer_id=gcp" \
            -var "region=us-central1" \
            -var "job_namespace=jobs"
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        run: |
          terraform apply "out.tfplan"
